// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.normandy.first_run", false);
user_pref("app.normandy.migrationsApplied", 10);
user_pref("app.normandy.startupRolloutPrefs.browser.toolbars.bookmarks.2h2020", true);
user_pref("app.normandy.user_id", "e9ca95d0-0261-4ea4-a2a1-2fb803abfd7a");
user_pref("app.update.lastUpdateTime.addon-background-update-timer", 0);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1610999542);
user_pref("app.update.lastUpdateTime.recipe-client-addon-run", 1610999660);
user_pref("app.update.lastUpdateTime.rs-experiment-loader-timer", 1610999514);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1610999662);
user_pref("app.update.lastUpdateTime.services-settings-poll-changes", 0);
user_pref("app.update.lastUpdateTime.telemetry_modules_ping", 1610999572);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 0);
user_pref("browser.bookmarks.addedImportButton", true);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.contentblocking.category", "standard");
user_pref("browser.download.panel.shown", true);
user_pref("browser.download.viewableInternally.typeWasRegistered.svg", true);
user_pref("browser.download.viewableInternally.typeWasRegistered.webp", true);
user_pref("browser.download.viewableInternally.typeWasRegistered.xml", true);
user_pref("browser.laterrun.bookkeeping.profileCreationTime", 1610999511);
user_pref("browser.laterrun.bookkeeping.sessionCount", 1);
user_pref("browser.laterrun.enabled", true);
user_pref("browser.migration.version", 104);
user_pref("browser.newtabpage.activity-stream.impressionId", "{5fc62895-0df6-40b1-9c40-bd5220ffb063}");
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pageActions.persistedActions", "{\"version\":1,\"ids\":[\"bookmark\",\"pinTab\",\"bookmarkSeparator\",\"copyURL\",\"emailLink\",\"addSearchEngine\",\"sendToDevice\",\"pocket\",\"screenshots_mozilla_org\"],\"idsInUrlbar\":[\"pocket\",\"bookmark\"]}");
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.safebrowsing.provider.google4.lastupdatetime", "1610999530276");
user_pref("browser.safebrowsing.provider.google4.nextupdatetime", "1611001316276");
user_pref("browser.safebrowsing.provider.mozilla.lastupdatetime", "1610999517018");
user_pref("browser.safebrowsing.provider.mozilla.nextupdatetime", "1611021117018");
user_pref("browser.search.region", "LV");
user_pref("browser.shell.mostRecentDateSetAsDefault", "1610999513");
user_pref("browser.slowStartup.averageTime", 1746);
user_pref("browser.slowStartup.samples", 1);
user_pref("browser.startup.homepage_override.buildID", "20210105180113");
user_pref("browser.startup.homepage_override.mstone", "84.0.2");
user_pref("browser.startup.lastColdStartupCheck", 1610999513);
user_pref("browser.uiCustomization.state", "{\"placements\":{\"widget-overflow-fixed-list\":[],\"nav-bar\":[\"back-button\",\"forward-button\",\"stop-reload-button\",\"home-button\",\"customizableui-special-spring1\",\"urlbar-container\",\"customizableui-special-spring2\",\"downloads-button\",\"library-button\",\"sidebar-button\",\"fxa-toolbar-menu-button\"],\"toolbar-menubar\":[\"menubar-items\"],\"TabsToolbar\":[\"tabbrowser-tabs\",\"new-tab-button\",\"alltabs-button\"],\"PersonalToolbar\":[\"import-button\",\"personal-bookmarks\"]},\"seen\":[\"developer-button\"],\"dirtyAreaCache\":[\"nav-bar\",\"PersonalToolbar\"],\"currentVersion\":16,\"newElementCount\":2}");
user_pref("browser.urlbar.placeholderName", "Google");
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 2);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1610999514175");
user_pref("distribution.canonical.bookmarksProcessed", true);
user_pref("distribution.iniFile.exists.appversion", "84.0.2");
user_pref("distribution.iniFile.exists.value", true);
user_pref("doh-rollout.balrog-migration-done", true);
user_pref("doh-rollout.doneFirstRun", true);
user_pref("dom.push.userAgentID", "7593646ca8694e049e00bbc6160c49af");
user_pref("extensions.activeThemeID", "default-theme@mozilla.org");
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.databaseSchema", 33);
user_pref("extensions.getAddons.databaseSchema", 6);
user_pref("extensions.incognito.migrated", true);
user_pref("extensions.lastAppVersion", "84.0.2");
user_pref("extensions.lastPlatformVersion", "84.0.2");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.webcompat.enable_picture_in_picture_overrides", true);
user_pref("extensions.webcompat.enable_shims", true);
user_pref("extensions.webcompat.perform_injections", true);
user_pref("extensions.webcompat.perform_ua_overrides", true);
user_pref("extensions.webextensions.ExtensionStorageIDB.migrated.screenshots@mozilla.org", true);
user_pref("extensions.webextensions.uuids", "{\"doh-rollout@mozilla.org\":\"c7f1e2d9-428f-4a4c-b99d-99159244e250\",\"formautofill@mozilla.org\":\"8423efd4-a1b4-4fee-8604-66f380bbaf75\",\"screenshots@mozilla.org\":\"6890ad25-5b7f-4ca8-b2d9-70ba8d4d7985\",\"webcompat-reporter@mozilla.org\":\"eabff207-77ad-49d7-9031-358ecad9e379\",\"webcompat@mozilla.org\":\"a366aed9-db31-42c8-8126-19a040cbf05a\",\"default-theme@mozilla.org\":\"37e95e36-db1b-42e2-94fd-9ece5c225bc3\",\"google@search.mozilla.org\":\"fbde78a4-0d73-49ca-af44-01909bedb90b\",\"amazondotcom@search.mozilla.org\":\"db579f8d-ea2d-4ab8-a057-19471f2f7a54\",\"wikipedia@search.mozilla.org\":\"dd90370e-69c9-4994-b9f7-10d02d16301f\",\"bing@search.mozilla.org\":\"3c8331c4-96f0-47bb-a774-1d19006909f2\",\"ddg@search.mozilla.org\":\"47e8273e-3bc5-4211-8431-f87a08387efd\"}");
user_pref("media.gmp.storage.version.observed", 1);
user_pref("network.trr.blocklist_cleanup_done", true);
user_pref("pdfjs.enabledCache.state", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("places.history.expiration.transient_current_max_pages", 112348);
user_pref("privacy.sanitize.pending", "[]");
user_pref("security.sandbox.content.tempDirSuffix", "129cc57f-e69e-4751-8175-c01f40dae18a");
user_pref("security.sandbox.plugin.tempDirSuffix", "04ae4a06-d14d-4f5c-84a8-a4af74b1c9a6");
user_pref("toolkit.startup.last_success", 1610999510);
user_pref("toolkit.telemetry.cachedClientID", "58975d27-8396-42ca-ad65-c8636d81b02d");
user_pref("toolkit.telemetry.previousBuildID", "20210105180113");
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
user_pref("trailhead.firstrun.didSeeAboutWelcome", true);
